import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.select import Select
s=Service("C:/TEST/chromedriver.exe")
driver = webdriver.Chrome(service=s)
driver.get("https://qa.neapro.site/login")
# АВТОРИЗАЦИЯ В ЛК
driver.maximize_window()
driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(1) input").click()
driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(1) input").send_keys("tester4545@yopmail.com")
driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(2) input").send_keys("--")
driver.find_element(By.CSS_SELECTOR, ".btn").click()
time.sleep(3)
# Заполнение ФОРМЫ ПАСПОРТ
driver.find_element(By.CSS_SELECTOR, ".form:nth-child(2) .document-tile:nth-child(1) > .document-name").click()
driver.find_element(By.ID, "surname").clear()
driver.find_element(By.ID, "surname").send_keys("Антонов")
driver.find_element(By.ID, "name").clear()
driver.find_element(By.ID, "name").send_keys("Антон")
driver.find_element(By.ID, "patronymic").clear()
driver.find_element(By.ID, "patronymic").send_keys("Антонович")
driver.find_element(By.NAME, "date").click()
driver.find_element(By.NAME, "date").clear()
#Дата рождения (data picker)
driver.find_element(By.NAME, "date").send_keys("22.04.1993")
#ПОЛЕ Паспорт серия
driver.find_element(By.ID, "passportSeries").click()
driver.find_element(By.ID, "passportSeries").clear()
driver.find_element(By.ID, "passportSeries").send_keys("3615")
#ПОЛЕ Паспорт номер
#time.sleep(5)
driver.find_element(By.ID, "passportNumber").click()
driver.find_element(By.ID, "passportNumber").clear()
driver.find_element(By.ID, "passportNumber").send_keys("371542")
#Дата выдачи(data picker)
#time.sleep(5)
driver.find_element(By.XPATH, '//*[@id="dateOfIssue"]/div/input').send_keys('18.04.2010')
#ПОЛЕ Код подразделения
#time.sleep(6)
driver.find_element(By.ID, "code").click()
driver.find_element(By.ID, "code").clear()
driver.find_element(By.ID, "code").send_keys("450005")
#ПОЛЕ Снилс
#time.sleep(3)
driver.find_element(By.ID, "cardId").click()
driver.find_element(By.ID, "cardId").clear()
driver.find_element(By.ID, "cardId").send_keys("14276854891")
#ПОЛЕ Кем выдан
#time.sleep(3)
driver.find_element(By.ID, "issued").click()
driver.find_element(By.ID, "issued").clear()
driver.find_element(By.ID, "issued").send_keys("Отделом УБГС по г.Кургану")
time.sleep(3)
#ПОЛЕ АДРЕС
address = driver.find_element(By.XPATH, '//*[@id="address"]/div/div/input')
address.send_keys(' ')
#address.send_keys('г Курган,ул Ленина, д 13')
address.click()
wait = WebDriverWait(driver, 2)
wait.until(EC.visibility_of_element_located((By.CLASS_NAME, 'vue-dadata__suggestions')))
address.send_keys(Keys.ARROW_DOWN)
address.send_keys(Keys.ENTER)
#Поле телефон
time.sleep(2)
driver.find_element(By.ID, "phone").click()
driver.find_element(By.ID, "phone").clear()
driver.find_element(By.ID, "phone").send_keys("9002586525")
#time.sleep(5)
#driver.find_element(By.CSS_SELECTOR,"#__layout > div > div.content-wrapper > div > div > div.content-page > div > div > div.form.passport-form.document-form > div.body > div.upload-widget.upload-widget > div > div > img").click()
#time.sleep(2)
driver.find_element(By.ID, "privacy").click()
driver.find_element(By.ID, "privacy").click()
#Прикрепить файл
time.sleep(4)
driver.find_element(By.XPATH, "//input[@type='file']").send_keys("C:/TEST/test.jpg")
#кнопка отправить
time.sleep(3)
driver.find_element(By.CSS_SELECTOR, ".btn.fill").click()
time.sleep(3)
#Прикрепление файлов Диплом
driver.find_element(By.CSS_SELECTOR, ".form:nth-child(2) .document-tile:nth-child(2) > .document-name").click()
time.sleep(2)
driver.find_element(By.XPATH, "//input[@type='file']").send_keys("C:/TEST/test.jpg")
time.sleep(5)
driver.find_element(By.CSS_SELECTOR, ".btn.fill").click()
time.sleep(3)
#Прикрепление файлов Договор
driver.find_element(By.CSS_SELECTOR, ".form:nth-child(3) .document-tile:nth-child(1) > .document-name").click()
time.sleep(3)
driver.find_element(By.XPATH, "//input[@type='file']").send_keys("C:/TEST/test.jpg")
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, ".btn.fill").click()
time.sleep(3)
#Прикрепление файлов Заявление
driver.find_element(By.CSS_SELECTOR, ".form:nth-child(3) .document-tile:nth-child(2) > .document-name").click()
time.sleep(2)
driver.find_element(By.XPATH, "//input[@type='file']").send_keys("C:/TEST/test.jpg")
time.sleep(3)
driver.find_element(By.CSS_SELECTOR, ".btn.fill").click()
time.sleep(3)
#Прикрепление файлов Согласие
time.sleep(3)
driver.find_element(By.CSS_SELECTOR, ".form:nth-child(3) .document-tile:nth-child(3) > .document-name").click()
driver.find_element(By.XPATH, "//input[@type='file']").send_keys("C:/TEST/test.jpg")
time.sleep(3)
driver.find_element(By.CSS_SELECTOR, ".btn.fill").click()
time.sleep(3)
#Подтверждения файлов в админке
driver.get("https://adminqa.neapro.site/login")
driver.maximize_window()
driver.find_element(By.ID, "admin_email").send_keys("moderat@neapro.ru")
driver.find_element(By.ID, "admin_password").send_keys("---")
driver.find_element(By.ID, "admin_submit_action").click()
time.sleep(3)
driver.get("https://adminqa.neapro.site/documents?q%5Buser_id_eq%5D=1969&commit=%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C&order=id_desc")
#Принять Согласие
time.sleep(3)
driver.find_element(By.XPATH, "//*[@id='documents_consent_14395']/td[6]/div/div[1]/span").click()
#time.sleep(3)
driver.find_element(By.XPATH, "/html/body/span/span/span[1]/input").send_keys("Принят")
driver.find_element(By.XPATH, "/html/body/span/span/span[1]/input").send_keys(Keys.ENTER)
#time.sleep(3)
#Принять Заявление
#time.sleep(3)
driver.find_element(By.XPATH, "//*[@id='documents_statement_14394']/td[6]/div/div[1]/span").click()
time.sleep(5)
driver.find_element(By.XPATH, "/html/body/span/span/span[1]/input").send_keys("Принят")
driver.find_element(By.XPATH, "/html/body/span/span/span[1]/input").send_keys(Keys.ENTER)
#time.sleep(3)
#Принять Договор
#time.sleep(3)
driver.find_element(By.XPATH, "//*[@id='documents_contract_14393']/td[6]/div/div[1]/span").click()
time.sleep(3)
driver.find_element(By.XPATH, "/html/body/span/span/span[1]/input").send_keys("Принят")
driver.find_element(By.XPATH, "/html/body/span/span/span[1]/input").send_keys(Keys.ENTER)
#time.sleep(3)
#Принять Диплом
time.sleep(3)
driver.find_element(By.XPATH, "//*[@id='documents_diploma_14392']/td[6]/div/div[1]/span").click()
time.sleep(3)
driver.find_element(By.XPATH, "/html/body/span/span/span[1]/input").send_keys("Принят")
driver.find_element(By.XPATH, "/html/body/span/span/span[1]/input").send_keys(Keys.ENTER)
#time.sleep(3)
#Принять Паспорт
#time.sleep(3)
driver.find_element(By.XPATH, "//*[@id='documents_passport_14391']/td[6]/div/div[1]/span").click()
#time.sleep(3)
driver.find_element(By.XPATH, "/html/body/span/span/span[1]/input").send_keys("Принят")
driver.find_element(By.XPATH, "/html/body/span/span/span[1]/input").send_keys(Keys.ENTER)
time.sleep(3)
#Изменение пароля
time.sleep(3)
driver.get("https://qa.neapro.site/login")
driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(1) input").click()
driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(1) input").send_keys("tester4545@yopmail.com")
driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(2) input").send_keys("---")
time.sleep(3)
driver.find_element(By.CSS_SELECTOR, ".btn").click()
time.sleep(3)
driver.find_element(By.CSS_SELECTOR, "#__layout > div > div.static-menu > div > div.scrollmenu").click()
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, "#__layout > div > div.static-menu > div > div.menu-header > div.registration__profile > a > div > span").click()
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, "#__layout > div > div.content-wrapper > div > div > div.content-page > ul > li:nth-child(2) > a").click()
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, "#__layout > div > div.content-wrapper > div > div > div.content-page > div > div > div > div.body > div:nth-child(2) > div > div").click()
driver.find_element(By.CSS_SELECTOR, "#oldPassword").send_keys(---)
driver.find_element(By.CSS_SELECTOR, "#newPassword").send_keys(--)
driver.find_element(By.CSS_SELECTOR, "#confirmPassword").send_keys(--)
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, "#__layout > div > div.content-wrapper > div > div > div.content-page > div > div > div > div.body > form > button").click()
driver.find_element(By.CSS_SELECTOR, "#__layout > div > div.static-menu > div > div.scrollmenu").click()
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, "#__layout > div > div.static-menu > div > div.menu-header > div.full-logo > div > div").click()